/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.ReservarAsiento;

/**
 *
 * @author CARLOS
 */
public class AsientosIdaRetorno extends javax.swing.JFrame {

    /**
     * Creates new form ReservarAsientoBus
     */
    public AsientosIdaRetorno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRutas = new javax.swing.JLabel();
        labelAsientos = new javax.swing.JLabel();
        labelPasajeros = new javax.swing.JLabel();
        labelConfirmacion = new javax.swing.JLabel();
        labelResultados = new javax.swing.JLabel();
        labelRetroalimentacion = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelAsientoIda = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelSegundoPiso = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonA21 = new javax.swing.JButton();
        botonA10 = new javax.swing.JButton();
        botonA11 = new javax.swing.JButton();
        botonA12 = new javax.swing.JButton();
        botonA14 = new javax.swing.JButton();
        botonA13 = new javax.swing.JButton();
        botonA16 = new javax.swing.JButton();
        botonA17 = new javax.swing.JButton();
        botonA19 = new javax.swing.JButton();
        botonA20 = new javax.swing.JButton();
        botonA23 = new javax.swing.JButton();
        botonA22 = new javax.swing.JButton();
        botonA15 = new javax.swing.JButton();
        botonA18 = new javax.swing.JButton();
        panelPrimerPiso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonA1 = new javax.swing.JButton();
        botonA8 = new javax.swing.JButton();
        botonA4 = new javax.swing.JButton();
        botonA7 = new javax.swing.JButton();
        botonA9 = new javax.swing.JButton();
        botonA6 = new javax.swing.JButton();
        botonA3 = new javax.swing.JButton();
        botonA2 = new javax.swing.JButton();
        botonA5 = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        panelAsientoRetorno = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        label11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label12 = new javax.swing.JLabel();
        panelSegundoPiso1 = new javax.swing.JPanel();
        label13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        botonA24 = new javax.swing.JButton();
        botonA25 = new javax.swing.JButton();
        botonA26 = new javax.swing.JButton();
        botonA27 = new javax.swing.JButton();
        botonA28 = new javax.swing.JButton();
        botonA29 = new javax.swing.JButton();
        botonA30 = new javax.swing.JButton();
        botonA31 = new javax.swing.JButton();
        botonA32 = new javax.swing.JButton();
        botonA33 = new javax.swing.JButton();
        botonA34 = new javax.swing.JButton();
        botonA35 = new javax.swing.JButton();
        botonA36 = new javax.swing.JButton();
        botonA37 = new javax.swing.JButton();
        panelPrimerPiso1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        botonA38 = new javax.swing.JButton();
        botonA39 = new javax.swing.JButton();
        botonA40 = new javax.swing.JButton();
        botonA41 = new javax.swing.JButton();
        botonA42 = new javax.swing.JButton();
        botonA43 = new javax.swing.JButton();
        botonA44 = new javax.swing.JButton();
        botonA45 = new javax.swing.JButton();
        botonA46 = new javax.swing.JButton();
        label14 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        botonContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(974, 690));
        setPreferredSize(new java.awt.Dimension(974, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRutas.setBackground(new java.awt.Color(255, 255, 0));
        labelRutas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelRutas.setForeground(new java.awt.Color(255, 255, 255));
        labelRutas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRutas.setText("<html><p align=center>Rutas</p></html>");
        labelRutas.setAlignmentX(1.0F);
        labelRutas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 110, 30));

        labelAsientos.setBackground(new java.awt.Color(255, 255, 0));
        labelAsientos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelAsientos.setForeground(new java.awt.Color(0, 0, 153));
        labelAsientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAsientos.setText("Asientos");
        labelAsientos.setAlignmentX(1.0F);
        labelAsientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelAsientos.setOpaque(true);
        getContentPane().add(labelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 17, 110, 30));

        labelPasajeros.setBackground(new java.awt.Color(255, 255, 0));
        labelPasajeros.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelPasajeros.setForeground(new java.awt.Color(255, 255, 255));
        labelPasajeros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPasajeros.setText("Pasajeros");
        labelPasajeros.setAlignmentX(1.0F);
        labelPasajeros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 17, 110, 30));

        labelConfirmacion.setBackground(new java.awt.Color(255, 255, 0));
        labelConfirmacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        labelConfirmacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmacion.setText("Confirmación");
        labelConfirmacion.setAlignmentX(1.0F);
        labelConfirmacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 17, 110, 30));

        labelResultados.setBackground(new java.awt.Color(255, 255, 0));
        labelResultados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelResultados.setForeground(new java.awt.Color(255, 255, 255));
        labelResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultados.setText("Resultados");
        labelResultados.setAlignmentX(1.0F);
        labelResultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 17, 110, 30));

        labelRetroalimentacion.setBackground(new java.awt.Color(0, 0, 102));
        labelRetroalimentacion.setForeground(new java.awt.Color(0, 0, 153));
        labelRetroalimentacion.setOpaque(true);
        getContentPane().add(labelRetroalimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 973, 62));

        jTabbedPane1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        panelAsientoIda.setMinimumSize(new java.awt.Dimension(857, 639));
        panelAsientoIda.setPreferredSize(new java.awt.Dimension(857, 639));
        panelAsientoIda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label5.setBackground(new java.awt.Color(153, 153, 153));
        label5.setOpaque(true);
        panelAsientoIda.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 170, 30, 30));

        label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/timon1.png"))); // NOI18N
        panelAsientoIda.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 173, -1, -1));

        label1.setBackground(new java.awt.Color(0, 0, 102));
        label1.setOpaque(true);
        panelAsientoIda.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 20, 240));

        label7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/escalera.png"))); // NOI18N
        panelAsientoIda.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 330, 40, 40));

        jLabel2.setBackground(new java.awt.Color(153, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><p>2do</p><p>Piso</p></html>");
        jLabel2.setOpaque(true);
        panelAsientoIda.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 42, 42));

        label2.setBackground(new java.awt.Color(0, 0, 102));
        label2.setOpaque(true);
        panelAsientoIda.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 20, 240));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><p>1er</p><p>Piso</p></html>");
        jLabel1.setOpaque(true);
        panelAsientoIda.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 260, 42, 42));

        panelSegundoPiso.setBackground(new java.awt.Color(204, 204, 255));
        panelSegundoPiso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/escalera.png"))); // NOI18N
        panelSegundoPiso.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 160, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/inodoro.png"))); // NOI18N
        panelSegundoPiso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 52, -1, -1));

        botonA21.setBackground(new java.awt.Color(13, 13, 77));
        botonA21.setForeground(new java.awt.Color(255, 255, 255));
        botonA21.setText("21");
        botonA21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 46, 30));

        botonA10.setBackground(new java.awt.Color(13, 13, 77));
        botonA10.setForeground(new java.awt.Color(255, 255, 255));
        botonA10.setText("10");
        botonA10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 46, 30));

        botonA11.setBackground(new java.awt.Color(13, 13, 77));
        botonA11.setForeground(new java.awt.Color(255, 255, 255));
        botonA11.setText("11");
        botonA11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 46, 30));

        botonA12.setBackground(new java.awt.Color(13, 13, 77));
        botonA12.setForeground(new java.awt.Color(255, 255, 255));
        botonA12.setText("12");
        botonA12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 46, 30));

        botonA14.setBackground(new java.awt.Color(13, 13, 77));
        botonA14.setForeground(new java.awt.Color(255, 255, 255));
        botonA14.setText("14");
        botonA14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 46, 30));

        botonA13.setBackground(new java.awt.Color(13, 13, 77));
        botonA13.setForeground(new java.awt.Color(255, 255, 255));
        botonA13.setText("13");
        botonA13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 46, 30));

        botonA16.setBackground(new java.awt.Color(13, 13, 77));
        botonA16.setForeground(new java.awt.Color(255, 255, 255));
        botonA16.setText("16");
        botonA16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 46, 30));

        botonA17.setBackground(new java.awt.Color(13, 13, 77));
        botonA17.setForeground(new java.awt.Color(255, 255, 255));
        botonA17.setText("17");
        botonA17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 46, 30));

        botonA19.setBackground(new java.awt.Color(13, 13, 77));
        botonA19.setForeground(new java.awt.Color(255, 255, 255));
        botonA19.setText("19");
        botonA19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 46, 30));

        botonA20.setBackground(new java.awt.Color(13, 13, 77));
        botonA20.setForeground(new java.awt.Color(255, 255, 255));
        botonA20.setText("20");
        botonA20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 46, 30));

        botonA23.setBackground(new java.awt.Color(13, 13, 77));
        botonA23.setForeground(new java.awt.Color(255, 255, 255));
        botonA23.setText("23");
        botonA23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 46, 30));

        botonA22.setBackground(new java.awt.Color(13, 13, 77));
        botonA22.setForeground(new java.awt.Color(255, 255, 255));
        botonA22.setText("22");
        botonA22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 46, 30));

        botonA15.setBackground(new java.awt.Color(13, 13, 77));
        botonA15.setForeground(new java.awt.Color(255, 255, 255));
        botonA15.setText("15");
        botonA15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 46, 30));

        botonA18.setBackground(new java.awt.Color(13, 13, 77));
        botonA18.setForeground(new java.awt.Color(255, 255, 255));
        botonA18.setText("18");
        botonA18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 46, 30));

        panelAsientoIda.add(panelSegundoPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 380, 200));

        panelPrimerPiso.setBackground(new java.awt.Color(255, 204, 51));
        panelPrimerPiso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/televisor.png"))); // NOI18N
        panelPrimerPiso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        botonA1.setBackground(new java.awt.Color(13, 13, 77));
        botonA1.setForeground(new java.awt.Color(255, 255, 255));
        botonA1.setText("1");
        botonA1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelPrimerPiso.add(botonA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 46, 30));

        botonA8.setBackground(new java.awt.Color(13, 13, 77));
        botonA8.setForeground(new java.awt.Color(255, 255, 255));
        botonA8.setText("8");
        botonA8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 46, 30));

        botonA4.setBackground(new java.awt.Color(13, 13, 77));
        botonA4.setForeground(new java.awt.Color(255, 255, 255));
        botonA4.setText("4");
        botonA4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 46, 30));

        botonA7.setBackground(new java.awt.Color(13, 13, 77));
        botonA7.setForeground(new java.awt.Color(255, 255, 255));
        botonA7.setText("7");
        botonA7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 46, 30));

        botonA9.setBackground(new java.awt.Color(13, 13, 77));
        botonA9.setForeground(new java.awt.Color(255, 255, 255));
        botonA9.setText("9");
        botonA9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 46, 30));

        botonA6.setBackground(new java.awt.Color(13, 13, 77));
        botonA6.setForeground(new java.awt.Color(255, 255, 255));
        botonA6.setText("6");
        botonA6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 46, 30));

        botonA3.setBackground(new java.awt.Color(13, 13, 77));
        botonA3.setForeground(new java.awt.Color(255, 255, 255));
        botonA3.setText("3");
        botonA3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 46, 30));

        botonA2.setBackground(new java.awt.Color(13, 13, 77));
        botonA2.setForeground(new java.awt.Color(255, 255, 255));
        botonA2.setText("2");
        botonA2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 46, 30));

        botonA5.setBackground(new java.awt.Color(13, 13, 77));
        botonA5.setForeground(new java.awt.Color(255, 255, 255));
        botonA5.setText("5");
        botonA5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 46, 30));

        panelAsientoIda.add(panelPrimerPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 220, 200));

        label3.setBackground(new java.awt.Color(249, 216, 151));
        label3.setOpaque(true);
        panelAsientoIda.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 750, 240));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        panelAsientoIda.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 780, 40));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        panelAsientoIda.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 420, 80));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable3);

        panelAsientoIda.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 290, 90));

        jScrollPane1.setViewportView(panelAsientoIda);

        jTabbedPane1.addTab("1. Seleccione asientos de ida", jScrollPane1);

        panelAsientoRetorno.setMinimumSize(new java.awt.Dimension(857, 639));
        panelAsientoRetorno.setPreferredSize(new java.awt.Dimension(857, 639));
        panelAsientoRetorno.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label8.setBackground(new java.awt.Color(153, 153, 153));
        label8.setOpaque(true);
        panelAsientoRetorno.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 177, 30, 30));

        label9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/timon2.png"))); // NOI18N
        panelAsientoRetorno.add(label9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, -1));

        label10.setBackground(new java.awt.Color(0, 0, 102));
        label10.setOpaque(true);
        panelAsientoRetorno.add(label10, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 20, 240));

        label11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/escalera.png"))); // NOI18N
        panelAsientoRetorno.add(label11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 40, 40));

        jLabel5.setBackground(new java.awt.Color(153, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("<html><p>2do</p><p>Piso</p></html>");
        jLabel5.setOpaque(true);
        panelAsientoRetorno.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 42, 42));

        jLabel6.setBackground(new java.awt.Color(153, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html><p>1er</p><p>Piso</p></html>");
        jLabel6.setOpaque(true);
        panelAsientoRetorno.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 42, 42));

        label12.setBackground(new java.awt.Color(0, 0, 102));
        label12.setOpaque(true);
        panelAsientoRetorno.add(label12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 20, 240));

        panelSegundoPiso1.setBackground(new java.awt.Color(204, 204, 255));
        panelSegundoPiso1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/escalera.png"))); // NOI18N
        panelSegundoPiso1.add(label13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/inodoro.png"))); // NOI18N
        panelSegundoPiso1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        botonA24.setBackground(new java.awt.Color(13, 13, 77));
        botonA24.setForeground(new java.awt.Color(255, 255, 255));
        botonA24.setText("21");
        botonA24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 46, 30));

        botonA25.setBackground(new java.awt.Color(13, 13, 77));
        botonA25.setForeground(new java.awt.Color(255, 255, 255));
        botonA25.setText("10");
        botonA25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA25, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 46, 30));

        botonA26.setBackground(new java.awt.Color(13, 13, 77));
        botonA26.setForeground(new java.awt.Color(255, 255, 255));
        botonA26.setText("11");
        botonA26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA26, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 46, 30));

        botonA27.setBackground(new java.awt.Color(13, 13, 77));
        botonA27.setForeground(new java.awt.Color(255, 255, 255));
        botonA27.setText("12");
        botonA27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA27, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 46, 30));

        botonA28.setBackground(new java.awt.Color(13, 13, 77));
        botonA28.setForeground(new java.awt.Color(255, 255, 255));
        botonA28.setText("14");
        botonA28.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 46, 30));

        botonA29.setBackground(new java.awt.Color(13, 13, 77));
        botonA29.setForeground(new java.awt.Color(255, 255, 255));
        botonA29.setText("13");
        botonA29.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 46, 30));

        botonA30.setBackground(new java.awt.Color(13, 13, 77));
        botonA30.setForeground(new java.awt.Color(255, 255, 255));
        botonA30.setText("16");
        botonA30.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA30, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 46, 30));

        botonA31.setBackground(new java.awt.Color(13, 13, 77));
        botonA31.setForeground(new java.awt.Color(255, 255, 255));
        botonA31.setText("17");
        botonA31.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA31, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 46, 30));

        botonA32.setBackground(new java.awt.Color(13, 13, 77));
        botonA32.setForeground(new java.awt.Color(255, 255, 255));
        botonA32.setText("19");
        botonA32.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA32, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 46, 30));

        botonA33.setBackground(new java.awt.Color(13, 13, 77));
        botonA33.setForeground(new java.awt.Color(255, 255, 255));
        botonA33.setText("20");
        botonA33.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA33, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 46, 30));

        botonA34.setBackground(new java.awt.Color(13, 13, 77));
        botonA34.setForeground(new java.awt.Color(255, 255, 255));
        botonA34.setText("23");
        botonA34.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 46, 30));

        botonA35.setBackground(new java.awt.Color(13, 13, 77));
        botonA35.setForeground(new java.awt.Color(255, 255, 255));
        botonA35.setText("22");
        botonA35.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA35, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 46, 30));

        botonA36.setBackground(new java.awt.Color(13, 13, 77));
        botonA36.setForeground(new java.awt.Color(255, 255, 255));
        botonA36.setText("15");
        botonA36.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA36, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 46, 30));

        botonA37.setBackground(new java.awt.Color(13, 13, 77));
        botonA37.setForeground(new java.awt.Color(255, 255, 255));
        botonA37.setText("18");
        botonA37.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso1.add(botonA37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 46, 30));

        panelAsientoRetorno.add(panelSegundoPiso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 380, 200));

        panelPrimerPiso1.setBackground(new java.awt.Color(255, 204, 51));
        panelPrimerPiso1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/televisor.png"))); // NOI18N
        panelPrimerPiso1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        botonA38.setBackground(new java.awt.Color(13, 13, 77));
        botonA38.setForeground(new java.awt.Color(255, 255, 255));
        botonA38.setText("1");
        botonA38.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelPrimerPiso1.add(botonA38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 46, 30));

        botonA39.setBackground(new java.awt.Color(13, 13, 77));
        botonA39.setForeground(new java.awt.Color(255, 255, 255));
        botonA39.setText("8");
        botonA39.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso1.add(botonA39, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 46, 30));

        botonA40.setBackground(new java.awt.Color(13, 13, 77));
        botonA40.setForeground(new java.awt.Color(255, 255, 255));
        botonA40.setText("4");
        botonA40.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso1.add(botonA40, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 46, 30));

        botonA41.setBackground(new java.awt.Color(13, 13, 77));
        botonA41.setForeground(new java.awt.Color(255, 255, 255));
        botonA41.setText("7");
        botonA41.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso1.add(botonA41, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 46, 30));

        botonA42.setBackground(new java.awt.Color(13, 13, 77));
        botonA42.setForeground(new java.awt.Color(255, 255, 255));
        botonA42.setText("9");
        botonA42.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso1.add(botonA42, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 46, 30));

        botonA43.setBackground(new java.awt.Color(13, 13, 77));
        botonA43.setForeground(new java.awt.Color(255, 255, 255));
        botonA43.setText("6");
        botonA43.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso1.add(botonA43, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 46, 30));

        botonA44.setBackground(new java.awt.Color(13, 13, 77));
        botonA44.setForeground(new java.awt.Color(255, 255, 255));
        botonA44.setText("3");
        botonA44.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso1.add(botonA44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 46, 30));

        botonA45.setBackground(new java.awt.Color(13, 13, 77));
        botonA45.setForeground(new java.awt.Color(255, 255, 255));
        botonA45.setText("2");
        botonA45.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso1.add(botonA45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 46, 30));

        botonA46.setBackground(new java.awt.Color(13, 13, 77));
        botonA46.setForeground(new java.awt.Color(255, 255, 255));
        botonA46.setText("5");
        botonA46.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso1.add(botonA46, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 46, 30));

        panelAsientoRetorno.add(panelPrimerPiso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 220, 200));

        label14.setBackground(new java.awt.Color(249, 216, 151));
        label14.setOpaque(true);
        panelAsientoRetorno.add(label14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 750, 240));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        panelAsientoRetorno.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 780, 40));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable5);

        panelAsientoRetorno.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 420, 80));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane8.setViewportView(jTable6);

        panelAsientoRetorno.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 290, 90));

        jScrollPane5.setViewportView(panelAsientoRetorno);

        jTabbedPane1.addTab("2. Seleccione asientos de retorno", jScrollPane5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 890, 460));

        botonContinuar.setBackground(new java.awt.Color(0, 0, 102));
        botonContinuar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonContinuar.setForeground(new java.awt.Color(255, 255, 255));
        botonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus.png"))); // NOI18N
        botonContinuar.setText("Continuar");
        getContentPane().add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 600, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsientosIdaRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsientosIdaRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsientosIdaRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsientosIdaRetorno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsientosIdaRetorno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonA1;
    private javax.swing.JButton botonA10;
    private javax.swing.JButton botonA11;
    private javax.swing.JButton botonA12;
    private javax.swing.JButton botonA13;
    private javax.swing.JButton botonA14;
    private javax.swing.JButton botonA15;
    private javax.swing.JButton botonA16;
    private javax.swing.JButton botonA17;
    private javax.swing.JButton botonA18;
    private javax.swing.JButton botonA19;
    private javax.swing.JButton botonA2;
    private javax.swing.JButton botonA20;
    private javax.swing.JButton botonA21;
    private javax.swing.JButton botonA22;
    private javax.swing.JButton botonA23;
    private javax.swing.JButton botonA24;
    private javax.swing.JButton botonA25;
    private javax.swing.JButton botonA26;
    private javax.swing.JButton botonA27;
    private javax.swing.JButton botonA28;
    private javax.swing.JButton botonA29;
    private javax.swing.JButton botonA3;
    private javax.swing.JButton botonA30;
    private javax.swing.JButton botonA31;
    private javax.swing.JButton botonA32;
    private javax.swing.JButton botonA33;
    private javax.swing.JButton botonA34;
    private javax.swing.JButton botonA35;
    private javax.swing.JButton botonA36;
    private javax.swing.JButton botonA37;
    private javax.swing.JButton botonA38;
    private javax.swing.JButton botonA39;
    private javax.swing.JButton botonA4;
    private javax.swing.JButton botonA40;
    private javax.swing.JButton botonA41;
    private javax.swing.JButton botonA42;
    private javax.swing.JButton botonA43;
    private javax.swing.JButton botonA44;
    private javax.swing.JButton botonA45;
    private javax.swing.JButton botonA46;
    private javax.swing.JButton botonA5;
    private javax.swing.JButton botonA6;
    private javax.swing.JButton botonA7;
    private javax.swing.JButton botonA8;
    private javax.swing.JButton botonA9;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label11;
    private javax.swing.JLabel label12;
    private javax.swing.JLabel label13;
    private javax.swing.JLabel label14;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JLabel labelAsientos;
    private javax.swing.JLabel labelConfirmacion;
    private javax.swing.JLabel labelPasajeros;
    private javax.swing.JLabel labelResultados;
    private javax.swing.JLabel labelRetroalimentacion;
    private javax.swing.JLabel labelRutas;
    private javax.swing.JPanel panelAsientoIda;
    private javax.swing.JPanel panelAsientoRetorno;
    private javax.swing.JPanel panelPrimerPiso;
    private javax.swing.JPanel panelPrimerPiso1;
    private javax.swing.JPanel panelSegundoPiso;
    private javax.swing.JPanel panelSegundoPiso1;
    // End of variables declaration//GEN-END:variables
}
