/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.ReservarAsiento;

/**
 *
 * @author CARLOS
 */
public class AsientosIda extends javax.swing.JFrame {

    /**
     * Creates new form ReservarAsientoBus
     */
    public AsientosIda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        botonContinuar = new javax.swing.JButton();
        label5 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelSegundoPiso = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonA21 = new javax.swing.JButton();
        botonA10 = new javax.swing.JButton();
        botonA11 = new javax.swing.JButton();
        botonA12 = new javax.swing.JButton();
        botonA14 = new javax.swing.JButton();
        botonA13 = new javax.swing.JButton();
        botonA16 = new javax.swing.JButton();
        botonA17 = new javax.swing.JButton();
        botonA19 = new javax.swing.JButton();
        botonA20 = new javax.swing.JButton();
        botonA23 = new javax.swing.JButton();
        botonA22 = new javax.swing.JButton();
        botonA15 = new javax.swing.JButton();
        botonA18 = new javax.swing.JButton();
        panelPrimerPiso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        botonA1 = new javax.swing.JButton();
        botonA8 = new javax.swing.JButton();
        botonA4 = new javax.swing.JButton();
        botonA7 = new javax.swing.JButton();
        botonA9 = new javax.swing.JButton();
        botonA6 = new javax.swing.JButton();
        botonA3 = new javax.swing.JButton();
        botonA2 = new javax.swing.JButton();
        botonA5 = new javax.swing.JButton();
        label3 = new javax.swing.JLabel();
        labelRutas = new javax.swing.JLabel();
        labelAsientos = new javax.swing.JLabel();
        labelPasajeros = new javax.swing.JLabel();
        labelResultados = new javax.swing.JLabel();
        labelConfirmacion = new javax.swing.JLabel();
        labelRetroalimentacion = new javax.swing.JLabel();
        botonAnterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(974, 690));
        setPreferredSize(new java.awt.Dimension(974, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 650, 40));

        botonContinuar.setBackground(new java.awt.Color(0, 0, 102));
        botonContinuar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonContinuar.setForeground(new java.awt.Color(255, 255, 255));
        botonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus.png"))); // NOI18N
        botonContinuar.setText("Continuar");
        getContentPane().add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, -1, 40));

        label5.setBackground(new java.awt.Color(153, 153, 153));
        label5.setOpaque(true);
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 275, 30, 30));

        label4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/timon1.png"))); // NOI18N
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, -1, -1));

        label1.setBackground(new java.awt.Color(0, 0, 102));
        label1.setOpaque(true);
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 20, 240));

        label7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/escalera.png"))); // NOI18N
        getContentPane().add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 440, 40, 40));

        jLabel2.setBackground(new java.awt.Color(153, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<html><p>2do</p><p>Piso</p></html>");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 42, 42));

        label2.setBackground(new java.awt.Color(0, 0, 102));
        label2.setOpaque(true);
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 20, 240));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><p>1er</p><p>Piso</p></html>");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 360, 42, 42));

        panelSegundoPiso.setBackground(new java.awt.Color(204, 204, 255));
        panelSegundoPiso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/escalera.png"))); // NOI18N
        panelSegundoPiso.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 160, 40, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/inodoro.png"))); // NOI18N
        panelSegundoPiso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 52, -1, -1));

        botonA21.setBackground(new java.awt.Color(13, 13, 77));
        botonA21.setForeground(new java.awt.Color(255, 255, 255));
        botonA21.setText("21");
        botonA21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 46, 30));

        botonA10.setBackground(new java.awt.Color(13, 13, 77));
        botonA10.setForeground(new java.awt.Color(255, 255, 255));
        botonA10.setText("10");
        botonA10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 46, 30));

        botonA11.setBackground(new java.awt.Color(13, 13, 77));
        botonA11.setForeground(new java.awt.Color(255, 255, 255));
        botonA11.setText("11");
        botonA11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 46, 30));

        botonA12.setBackground(new java.awt.Color(13, 13, 77));
        botonA12.setForeground(new java.awt.Color(255, 255, 255));
        botonA12.setText("12");
        botonA12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 46, 30));

        botonA14.setBackground(new java.awt.Color(13, 13, 77));
        botonA14.setForeground(new java.awt.Color(255, 255, 255));
        botonA14.setText("14");
        botonA14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 46, 30));

        botonA13.setBackground(new java.awt.Color(13, 13, 77));
        botonA13.setForeground(new java.awt.Color(255, 255, 255));
        botonA13.setText("13");
        botonA13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 46, 30));

        botonA16.setBackground(new java.awt.Color(13, 13, 77));
        botonA16.setForeground(new java.awt.Color(255, 255, 255));
        botonA16.setText("16");
        botonA16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 46, 30));

        botonA17.setBackground(new java.awt.Color(13, 13, 77));
        botonA17.setForeground(new java.awt.Color(255, 255, 255));
        botonA17.setText("17");
        botonA17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 46, 30));

        botonA19.setBackground(new java.awt.Color(13, 13, 77));
        botonA19.setForeground(new java.awt.Color(255, 255, 255));
        botonA19.setText("19");
        botonA19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA19, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 46, 30));

        botonA20.setBackground(new java.awt.Color(13, 13, 77));
        botonA20.setForeground(new java.awt.Color(255, 255, 255));
        botonA20.setText("20");
        botonA20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA20, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 46, 30));

        botonA23.setBackground(new java.awt.Color(13, 13, 77));
        botonA23.setForeground(new java.awt.Color(255, 255, 255));
        botonA23.setText("23");
        botonA23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 46, 30));

        botonA22.setBackground(new java.awt.Color(13, 13, 77));
        botonA22.setForeground(new java.awt.Color(255, 255, 255));
        botonA22.setText("22");
        botonA22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 46, 30));

        botonA15.setBackground(new java.awt.Color(13, 13, 77));
        botonA15.setForeground(new java.awt.Color(255, 255, 255));
        botonA15.setText("15");
        botonA15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 46, 30));

        botonA18.setBackground(new java.awt.Color(13, 13, 77));
        botonA18.setForeground(new java.awt.Color(255, 255, 255));
        botonA18.setText("18");
        botonA18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelSegundoPiso.add(botonA18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 46, 30));

        getContentPane().add(panelSegundoPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 380, 200));

        panelPrimerPiso.setBackground(new java.awt.Color(255, 204, 51));
        panelPrimerPiso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/televisor.png"))); // NOI18N
        panelPrimerPiso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        botonA1.setBackground(new java.awt.Color(13, 13, 77));
        botonA1.setForeground(new java.awt.Color(255, 255, 255));
        botonA1.setText("1");
        botonA1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelPrimerPiso.add(botonA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 46, 30));

        botonA8.setBackground(new java.awt.Color(13, 13, 77));
        botonA8.setForeground(new java.awt.Color(255, 255, 255));
        botonA8.setText("8");
        botonA8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 46, 30));

        botonA4.setBackground(new java.awt.Color(13, 13, 77));
        botonA4.setForeground(new java.awt.Color(255, 255, 255));
        botonA4.setText("4");
        botonA4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 46, 30));

        botonA7.setBackground(new java.awt.Color(13, 13, 77));
        botonA7.setForeground(new java.awt.Color(255, 255, 255));
        botonA7.setText("7");
        botonA7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 46, 30));

        botonA9.setBackground(new java.awt.Color(13, 13, 77));
        botonA9.setForeground(new java.awt.Color(255, 255, 255));
        botonA9.setText("9");
        botonA9.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 46, 30));

        botonA6.setBackground(new java.awt.Color(13, 13, 77));
        botonA6.setForeground(new java.awt.Color(255, 255, 255));
        botonA6.setText("6");
        botonA6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 46, 30));

        botonA3.setBackground(new java.awt.Color(13, 13, 77));
        botonA3.setForeground(new java.awt.Color(255, 255, 255));
        botonA3.setText("3");
        botonA3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 46, 30));

        botonA2.setBackground(new java.awt.Color(13, 13, 77));
        botonA2.setForeground(new java.awt.Color(255, 255, 255));
        botonA2.setText("2");
        botonA2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 46, 30));

        botonA5.setBackground(new java.awt.Color(13, 13, 77));
        botonA5.setForeground(new java.awt.Color(255, 255, 255));
        botonA5.setText("5");
        botonA5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPrimerPiso.add(botonA5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 46, 30));

        getContentPane().add(panelPrimerPiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 220, 200));

        label3.setBackground(new java.awt.Color(249, 216, 151));
        label3.setOpaque(true);
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 750, 240));

        labelRutas.setBackground(new java.awt.Color(255, 255, 0));
        labelRutas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelRutas.setForeground(new java.awt.Color(255, 255, 255));
        labelRutas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRutas.setText("<html><p align=center>Rutas</p></html>");
        labelRutas.setAlignmentX(1.0F);
        labelRutas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 110, 30));

        labelAsientos.setBackground(new java.awt.Color(255, 255, 0));
        labelAsientos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelAsientos.setForeground(new java.awt.Color(0, 0, 153));
        labelAsientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAsientos.setText("Asientos");
        labelAsientos.setAlignmentX(1.0F);
        labelAsientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelAsientos.setOpaque(true);
        getContentPane().add(labelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 17, 110, 30));

        labelPasajeros.setBackground(new java.awt.Color(255, 255, 0));
        labelPasajeros.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelPasajeros.setForeground(new java.awt.Color(255, 255, 255));
        labelPasajeros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPasajeros.setText("Pasajeros");
        labelPasajeros.setAlignmentX(1.0F);
        labelPasajeros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 17, 110, 30));

        labelResultados.setBackground(new java.awt.Color(255, 255, 0));
        labelResultados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelResultados.setForeground(new java.awt.Color(255, 255, 255));
        labelResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultados.setText("Resultados");
        labelResultados.setAlignmentX(1.0F);
        labelResultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 17, 110, 30));

        labelConfirmacion.setBackground(new java.awt.Color(255, 255, 0));
        labelConfirmacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        labelConfirmacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmacion.setText("Confirmación");
        labelConfirmacion.setAlignmentX(1.0F);
        labelConfirmacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 17, 110, 30));

        labelRetroalimentacion.setBackground(new java.awt.Color(0, 0, 102));
        labelRetroalimentacion.setForeground(new java.awt.Color(0, 0, 153));
        labelRetroalimentacion.setOpaque(true);
        getContentPane().add(labelRetroalimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 973, 62));

        botonAnterior.setBackground(new java.awt.Color(0, 0, 102));
        botonAnterior.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonAnterior.setForeground(new java.awt.Color(255, 255, 255));
        botonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus2.png"))); // NOI18N
        botonAnterior.setText("Regresar");
        getContentPane().add(botonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, -1, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsientosIda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsientosIda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsientosIda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsientosIda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsientosIda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonA1;
    private javax.swing.JButton botonA10;
    private javax.swing.JButton botonA11;
    private javax.swing.JButton botonA12;
    private javax.swing.JButton botonA13;
    private javax.swing.JButton botonA14;
    private javax.swing.JButton botonA15;
    private javax.swing.JButton botonA16;
    private javax.swing.JButton botonA17;
    private javax.swing.JButton botonA18;
    private javax.swing.JButton botonA19;
    private javax.swing.JButton botonA2;
    private javax.swing.JButton botonA20;
    private javax.swing.JButton botonA21;
    private javax.swing.JButton botonA22;
    private javax.swing.JButton botonA23;
    private javax.swing.JButton botonA3;
    private javax.swing.JButton botonA4;
    private javax.swing.JButton botonA5;
    private javax.swing.JButton botonA6;
    private javax.swing.JButton botonA7;
    private javax.swing.JButton botonA8;
    private javax.swing.JButton botonA9;
    private javax.swing.JButton botonAnterior;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel labelAsientos;
    private javax.swing.JLabel labelConfirmacion;
    private javax.swing.JLabel labelPasajeros;
    private javax.swing.JLabel labelResultados;
    private javax.swing.JLabel labelRetroalimentacion;
    private javax.swing.JLabel labelRutas;
    private javax.swing.JPanel panelPrimerPiso;
    private javax.swing.JPanel panelSegundoPiso;
    // End of variables declaration//GEN-END:variables
}
