/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.ReservarAsiento;

import java.awt.Dimension;

/**
 *
 * @author CARLOS
 */
public class PasajerosIda extends javax.swing.JFrame {
    private int cantidadAsientos;
    private panelPasajero pasajeros[];
    public PasajerosIda() {
        initComponents();
        panelAsientoIda.setLayout(null);
        panelPasajero p = new panelPasajero();
        p.labelAsiento.setText("<html><p align=center>Asiento</p><p align=center>21</p></html>");
        p.setBounds(6, 5, 857, 417);
        panelAsientoIda.setSize(870, 1400);
         panelAsientoIda.add(p); 
        panelPasajero p2 = new panelPasajero();
        p2.setBounds(6, 425, 857, 417);
        panelAsientoIda.add(p2);        
        panelAsientoIda.setPreferredSize(new Dimension(857, 2400));
        panelAsientoIda.repaint();
        System.out.println("hoar" + panelAsientoIda.getSize());
        
    }
    
    public PasajerosIda(int asientos){
        initComponents();
        cantidadAsientos = asientos;
        pasajeros = new panelPasajero[cantidadAsientos];
        int a = 857;
        int b = 417;
        int c = 5;
        panelAsientoIda.setPreferredSize(new Dimension(857, 417 * cantidadAsientos));
        for (int i = 0; i < cantidadAsientos; i++) {
            pasajeros[i] = new panelPasajero();
            pasajeros[i].setBounds(6, c, a, b);
            c += b;
            panelAsientoIda.add(pasajeros[i]);
        }
        panelAsientoIda.repaint();      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRutas = new javax.swing.JLabel();
        labelAsientos = new javax.swing.JLabel();
        labelPasajeros = new javax.swing.JLabel();
        labelConfirmacion = new javax.swing.JLabel();
        labelResultados = new javax.swing.JLabel();
        labelRetroalimentacion = new javax.swing.JLabel();
        botonContinuar = new javax.swing.JButton();
        panelDetalleItinerario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelIda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableItinerarioIda = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        labelRetorno = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableItinerarioRetorno = new javax.swing.JTable();
        botonRetroceder = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        panelAsientoIda = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(974, 720));
        setPreferredSize(new java.awt.Dimension(973, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRutas.setBackground(new java.awt.Color(255, 255, 0));
        labelRutas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelRutas.setForeground(new java.awt.Color(255, 255, 255));
        labelRutas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRutas.setText("<html><p align=center>Rutas</p></html>");
        labelRutas.setAlignmentX(1.0F);
        labelRutas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 17, 110, 30));

        labelAsientos.setBackground(new java.awt.Color(255, 255, 0));
        labelAsientos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelAsientos.setForeground(new java.awt.Color(255, 255, 255));
        labelAsientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAsientos.setText("Asientos");
        labelAsientos.setAlignmentX(1.0F);
        labelAsientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 17, 110, 30));

        labelPasajeros.setBackground(new java.awt.Color(255, 255, 0));
        labelPasajeros.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelPasajeros.setForeground(new java.awt.Color(0, 0, 153));
        labelPasajeros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPasajeros.setText("Pasajeros");
        labelPasajeros.setAlignmentX(1.0F);
        labelPasajeros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelPasajeros.setOpaque(true);
        getContentPane().add(labelPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 17, 110, 30));

        labelConfirmacion.setBackground(new java.awt.Color(255, 255, 0));
        labelConfirmacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        labelConfirmacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmacion.setText("Confirmación");
        labelConfirmacion.setAlignmentX(1.0F);
        labelConfirmacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 17, 110, 30));

        labelResultados.setBackground(new java.awt.Color(255, 255, 0));
        labelResultados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelResultados.setForeground(new java.awt.Color(255, 255, 255));
        labelResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultados.setText("Resultados");
        labelResultados.setAlignmentX(1.0F);
        labelResultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 17, 110, 30));

        labelRetroalimentacion.setBackground(new java.awt.Color(0, 0, 102));
        labelRetroalimentacion.setForeground(new java.awt.Color(0, 0, 153));
        labelRetroalimentacion.setOpaque(true);
        getContentPane().add(labelRetroalimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 973, 62));

        botonContinuar.setBackground(new java.awt.Color(0, 0, 102));
        botonContinuar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonContinuar.setForeground(new java.awt.Color(255, 255, 255));
        botonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus.png"))); // NOI18N
        botonContinuar.setText("Continuar");
        getContentPane().add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 620, -1, 40));

        panelDetalleItinerario.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Detalla de Itinerario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        panelDetalleItinerario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus4.png"))); // NOI18N
        jLabel1.setText("                  Itinerario de Retorno:");
        panelDetalleItinerario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        labelIda.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        panelDetalleItinerario.add(labelIda, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 160, 30));

        tableItinerarioIda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableItinerarioIda);

        panelDetalleItinerario.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 600, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus3.png"))); // NOI18N
        jLabel2.setText("                  Itinerario de Ida:");
        panelDetalleItinerario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        labelRetorno.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        panelDetalleItinerario.add(labelRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 160, 30));

        tableItinerarioRetorno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableItinerarioRetorno);

        panelDetalleItinerario.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 600, 40));

        getContentPane().add(panelDetalleItinerario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 880, 240));

        botonRetroceder.setBackground(new java.awt.Color(0, 0, 102));
        botonRetroceder.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonRetroceder.setForeground(new java.awt.Color(255, 255, 255));
        botonRetroceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus2.png"))); // NOI18N
        botonRetroceder.setText("Retroceder");
        getContentPane().add(botonRetroceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 620, -1, 40));

        javax.swing.GroupLayout panelAsientoIdaLayout = new javax.swing.GroupLayout(panelAsientoIda);
        panelAsientoIda.setLayout(panelAsientoIdaLayout);
        panelAsientoIdaLayout.setHorizontalGroup(
            panelAsientoIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 877, Short.MAX_VALUE)
        );
        panelAsientoIdaLayout.setVerticalGroup(
            panelAsientoIdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(panelAsientoIda);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 880, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasajerosIda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasajerosIda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasajerosIda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasajerosIda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PasajerosIda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonContinuar;
    private javax.swing.JButton botonRetroceder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelAsientos;
    private javax.swing.JLabel labelConfirmacion;
    private javax.swing.JLabel labelIda;
    private javax.swing.JLabel labelPasajeros;
    private javax.swing.JLabel labelResultados;
    private javax.swing.JLabel labelRetorno;
    private javax.swing.JLabel labelRetroalimentacion;
    private javax.swing.JLabel labelRutas;
    private javax.swing.JPanel panelAsientoIda;
    private javax.swing.JPanel panelDetalleItinerario;
    private javax.swing.JTable tableItinerarioIda;
    private javax.swing.JTable tableItinerarioRetorno;
    // End of variables declaration//GEN-END:variables
}
