/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame.ReservarAsiento;

/**
 *
 * @author CARLOS
 */
public class Rutas extends javax.swing.JFrame {

    /**
     * Creates new form ReservarAsientoBus
     */
    public Rutas() {
        initComponents();
        panelResultadosBusqueda.setVisible(false);
        botonContinuar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRutas = new javax.swing.JLabel();
        labelAsientos = new javax.swing.JLabel();
        panelResultadosBusqueda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIda = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRetorno = new javax.swing.JTable();
        panelDatosViaje = new javax.swing.JPanel();
        radioIdaRetorno = new javax.swing.JRadioButton();
        radioIda = new javax.swing.JRadioButton();
        labelInicio = new javax.swing.JLabel();
        labelFin = new javax.swing.JLabel();
        labelFechaIda = new javax.swing.JLabel();
        labelFechaRetorno = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        comboOrigen = new javax.swing.JComboBox<>();
        comboDestino = new javax.swing.JComboBox<>();
        fechaRetorno = new com.toedter.calendar.JDateChooser();
        fechaIda = new com.toedter.calendar.JDateChooser();
        botonContinuar = new javax.swing.JButton();
        labelResultados = new javax.swing.JLabel();
        labelConfirmacion = new javax.swing.JLabel();
        labelPasajeros = new javax.swing.JLabel();
        labelRetroalimentacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(974, 690));
        setPreferredSize(new java.awt.Dimension(974, 690));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelRutas.setBackground(new java.awt.Color(255, 255, 0));
        labelRutas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelRutas.setForeground(new java.awt.Color(0, 0, 153));
        labelRutas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelRutas.setText("<html><p align=center>Rutas</p></html>");
        labelRutas.setAlignmentX(1.0F);
        labelRutas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelRutas.setOpaque(true);
        getContentPane().add(labelRutas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 17, 110, 30));

        labelAsientos.setBackground(new java.awt.Color(255, 255, 0));
        labelAsientos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelAsientos.setForeground(new java.awt.Color(255, 255, 255));
        labelAsientos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelAsientos.setText("Asientos");
        labelAsientos.setAlignmentX(1.0F);
        labelAsientos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelAsientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 17, 110, 30));

        panelResultadosBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Resultados de búsqueda", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        panelResultadosBusqueda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaIda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title3", "Asientos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaIda);

        panelResultadosBusqueda.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 780, 50));

        tablaRetorno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaRetorno);

        panelResultadosBusqueda.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 770, 50));

        getContentPane().add(panelResultadosBusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 860, 240));

        panelDatosViaje.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Ingrese datos de viaje", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        panelDatosViaje.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        radioIdaRetorno.setSelected(true);
        radioIdaRetorno.setText("Ida y retorno");
        radioIdaRetorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIdaRetornoActionPerformed(evt);
            }
        });
        panelDatosViaje.add(radioIdaRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        radioIda.setText("Solo ida");
        radioIda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioIdaActionPerformed(evt);
            }
        });
        panelDatosViaje.add(radioIda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        labelInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/iniciar.png"))); // NOI18N
        labelInicio.setText("Origen");
        panelDatosViaje.add(labelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, -1));

        labelFin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/terminar.png"))); // NOI18N
        labelFin.setText("Fin");
        panelDatosViaje.add(labelFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 90, -1));

        labelFechaIda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/autobus.png"))); // NOI18N
        labelFechaIda.setText("Fecha ida");
        panelDatosViaje.add(labelFechaIda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 90, -1));

        labelFechaRetorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus5.png"))); // NOI18N
        labelFechaRetorno.setText("Fecha retorno");
        panelDatosViaje.add(labelFechaRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 110, -1));

        botonBuscar.setBackground(new java.awt.Color(0, 0, 102));
        botonBuscar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/icono-de-lupa.png"))); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        panelDatosViaje.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, -1, 40));

        comboOrigen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lima (Arriola)", "Chiclayo", "Piura", "Trujillo", "Chimbote" }));
        panelDatosViaje.add(comboOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 25));

        comboDestino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lima (Arriola)", "Chiclayo", "Piura", "Trujillo", "Chimbote" }));
        comboDestino.setSelectedIndex(1);
        panelDatosViaje.add(comboDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, 25));
        panelDatosViaje.add(fechaRetorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 110, 25));
        panelDatosViaje.add(fechaIda, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 110, 25));

        getContentPane().add(panelDatosViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 860, 200));

        botonContinuar.setBackground(new java.awt.Color(0, 0, 102));
        botonContinuar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonContinuar.setForeground(new java.awt.Color(255, 255, 255));
        botonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frame/imagenes/iconos/bus.png"))); // NOI18N
        botonContinuar.setText("Continuar");
        getContentPane().add(botonContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, -1, 40));

        labelResultados.setBackground(new java.awt.Color(255, 255, 0));
        labelResultados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelResultados.setForeground(new java.awt.Color(255, 255, 255));
        labelResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultados.setText("Resultados");
        labelResultados.setAlignmentX(1.0F);
        labelResultados.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 17, 110, 30));

        labelConfirmacion.setBackground(new java.awt.Color(255, 255, 0));
        labelConfirmacion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelConfirmacion.setForeground(new java.awt.Color(255, 255, 255));
        labelConfirmacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConfirmacion.setText("Confirmación");
        labelConfirmacion.setAlignmentX(1.0F);
        labelConfirmacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelConfirmacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 17, 110, 30));

        labelPasajeros.setBackground(new java.awt.Color(255, 255, 0));
        labelPasajeros.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        labelPasajeros.setForeground(new java.awt.Color(255, 255, 255));
        labelPasajeros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPasajeros.setText("Pasajeros");
        labelPasajeros.setAlignmentX(1.0F);
        labelPasajeros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelPasajeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 17, 110, 30));

        labelRetroalimentacion.setBackground(new java.awt.Color(0, 0, 102));
        labelRetroalimentacion.setForeground(new java.awt.Color(0, 0, 153));
        labelRetroalimentacion.setOpaque(true);
        getContentPane().add(labelRetroalimentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 973, 62));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioIdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIdaActionPerformed
        labelFechaRetorno.setEnabled(false);
        fechaRetorno.setEnabled(false);
        radioIdaRetorno.setSelected(false);
    }//GEN-LAST:event_radioIdaActionPerformed

    private void radioIdaRetornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioIdaRetornoActionPerformed
        labelFechaRetorno.setEnabled(true);
        fechaRetorno.setEnabled(true);
        radioIda.setSelected(false);
    }//GEN-LAST:event_radioIdaRetornoActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        panelResultadosBusqueda.setVisible(true);
        botonContinuar.setVisible(true);
    }//GEN-LAST:event_botonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rutas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Rutas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonContinuar;
    private javax.swing.JComboBox<String> comboDestino;
    private javax.swing.JComboBox<String> comboOrigen;
    private com.toedter.calendar.JDateChooser fechaIda;
    private com.toedter.calendar.JDateChooser fechaRetorno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAsientos;
    private javax.swing.JLabel labelConfirmacion;
    private javax.swing.JLabel labelFechaIda;
    private javax.swing.JLabel labelFechaRetorno;
    private javax.swing.JLabel labelFin;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JLabel labelPasajeros;
    private javax.swing.JLabel labelResultados;
    private javax.swing.JLabel labelRetroalimentacion;
    private javax.swing.JLabel labelRutas;
    private javax.swing.JPanel panelDatosViaje;
    private javax.swing.JPanel panelResultadosBusqueda;
    private javax.swing.JRadioButton radioIda;
    private javax.swing.JRadioButton radioIdaRetorno;
    private javax.swing.JTable tablaIda;
    private javax.swing.JTable tablaRetorno;
    // End of variables declaration//GEN-END:variables
}
